### ISSUE TITLE
QQ邮箱一直提示帐户名密码错误。

### ISSUE THREAD

**Issue by DrayChou** [Jackeriss/Email_My_PC#1]
客户端里已经可以正常登陆。
[mail]
popserver = pop.qq.com
smtpserver = smtp.qq.com

另外，你把密码就这样明文存在文本里好吗？

**Comment by Jackeriss** [comment]
谢谢提醒！当然不好了，是我忘记写加密了，现在官网上的版本已经是带加密版的了，带加密版的源码就不公开了，免得别人随便解密。。。密码错误问题多半是没有使用客户端授权密码导致的。请按说明书开启邮箱的POP/SMTP服务，并获取客户端授权密码。

**Comment by xiehongyu2005** [comment]
官网还是没有加密的

**Comment by DrayChou** [comment]
@Jackeriss 又下了一次，确认官网下载的是没有加密的。
另外，应该是支持 pop/smtp 协议的邮箱都可以吧？国内的邮箱现在申请开启授权什么的都要实名认证验证手机什么的了，但是这些都已经被占用了，申请新邮箱忒麻烦了。

**Comment by Jackeriss** [comment]
现在官网应该是有加密的了。版本号1.0.1，还解决了可以重复打开多个进程的问题。

**Comment by DrayChou** [comment]
@Jackeriss 重新下载了，然后应用的关于里看到版本号还是 1.0.0，但是密码确实不是明文的了。
申请了 hotmail 的邮箱，现在就一直显示正在连接了，也没有提示密码错误。

**Comment by Jackeriss** [comment]
哦，配置文件忘记改版本号了，我这记性真是。。。

**Comment by DrayChou** [comment]
@Jackeriss hotmail 的 pop3 协议支持如何？
[mail]
popserver = pop-mail.outlook.com
smtpserver = smtp-mail.outlook.com
