### ISSUE TITLE
支持 hotmail/outlook 吗？

### ISSUE THREAD

**Issue by DrayChou** [Jackeriss/Email_My_PC#3]
[mail]
popserver = pop-mail.outlook.com
smtpserver = smtp-mail.outlook.com

以上是 hotmail/outlook 邮箱的配置。
目前主界面的服务是显示开启状态的，但是发送任何命令过去都没有回应。
foxmail是能收到邮件的。

官网配置：
伺服器名稱: smtp-mail.outlook.com
連接埠: 587
加密方法: TLS

伺服器名稱: pop-mail.outlook.com
連接埠: 995
加密方法: SSL

**Comment by Jackeriss** [comment]
outlook是不是没有提供客户端授权密码，我直接使用的邮箱密码。结果在连接pop服务器时，python的poplib模块在调用socket模块时报错，无法建立连接。

**Comment by DrayChou** [comment]
我也是用的邮箱密码。
没有看到有说客户端授权密码这个东西。

Jack Criss notifications@github.com 於 2016年2月14日 週日 下午4:28寫道：

**Comment by DrayChou** [comment]
@Jackeriss 有什么办法能解决吗？

**Comment by Jackeriss** [comment]
你可以试试将其他邮箱绑定到outlook邮箱上，用outlook收发其他邮箱的邮件。目前程序上没有什么好的解决方法。

**Comment by Jackeriss** [comment]
目前QQ邮箱的支持最好，可以0间隔接收邮件，还可以用微信直接收发，如果没有特殊原因推荐使用QQ邮箱。

**Comment by DrayChou** [comment]
@Jackeriss 
QQ 邮箱的问题是：
1. 我当前正在使用的QQ账号不放心拿来做这个。或者我当前的QQ邮箱就是我要发邮件的邮箱。
2. 新申请的邮箱默认 pop 开关是关闭的，要打开的话必须实名认证并且验证手机，而手机已经绑定在主QQ号码上了，所以验证失败。
3. 于是卡在这里。

**Comment by Jackeriss** [comment]
你说的QQ邮箱申请授权密码被占用是什么情况，不是可以重新申请吗？

**Comment by Jackeriss** [comment]
嗯，明白了。

**Comment by DrayChou** [comment]
你的邮件不是发给邮件发送方啊？而是发给设置里填的邮箱啊？这样不是自己发给自己吗？

**Comment by Jackeriss** [comment]
就是自己发给自己啊

**Comment by DrayChou** [comment]
噗，不是谁发的邮件会给谁吗？

Jack Criss notifications@github.com 於 2016年2月14日週日 18:48 寫道：

**Comment by Jackeriss** [comment]
一个邮箱能够解决的问题为啥非得用俩？大部分人也是常用一个邮箱。

**Comment by DrayChou** [comment]
@Jackeriss 不是这么说的啊。
之所以要回给发信人，是因为一般人是不会把自己的主邮箱的账号密码填在这里来的，太容易暴露了。

**Comment by Jackeriss** [comment]
@DrayChou 那要是回给发信人的话就要强制设置白名单了，否则别人给你发封邮件就能看到你的隐私。
而且在自己的电脑上使用怎么会暴露呢？

**Comment by DrayChou** [comment]
因为并不是每个人都放心把密码写出来的啊。白名单是一定要设置的，要不然怎么回复开机启动命令。
这样也方便多人或者多邮箱共同管理一台机器。
比如：实验室里的一台电脑跑大家都关心的一个程序任务，那么所有人都可以随时看到任务进度了。

Jack Criss notifications@github.com 於 2016年2月15日 週一 上午10:12寫道：

**Comment by Jackeriss** [comment]
@DrayChou 共同监控一台电脑的使用场景确实不多，就算是团体项目也是各有分工，一个人负责就行了，所以我感觉没必要，反而增加了使用难度，牺牲了用户友好性。而且所有隐私信息都已经经过了加密处理，除非是有目的的入侵和破译，信息是不可能泄露的。如果你的电脑都被入侵了，还有什么隐私可言？所以我还是觉得应该给自己发邮件。

**Comment by Jackeriss** [comment]
共同监控一台电脑的使用场景确实不多，就算是团体项目也是各有分工，一个人负责就行了，所以我感觉没必要，反而增加了使用难度，牺牲了用户友好性。而且所有隐私信息都已经经过了加密处理，除非是有目的的入侵和破译，信息是不可能泄露的。所以我还是觉得应该给自己发邮件。

**Comment by DrayChou** [comment]
这个就是理念的问题了。
还是回归正题吧，对于 outlook 的支持能做吗？

Jack Criss notifications@github.com 於 2016年2月15日 週一 下午5:29寫道：

**Comment by Jackeriss** [comment]
@DrayChou 很抱歉，socket模块连接超时，我也解决不了。感谢你对我的支持，发现了许多不足，也提了很多建议，谢谢。

**Comment by DrayChou** [comment]
也谢谢你的工作和你的分享。

Jack Criss notifications@github.com 於 2016年2月16日 週二 下午1:24寫道：

**Comment by DrayChou** [comment]
http://stackoverflow.com/questions/30314618/having-trouble-with-sending-an-email-through-smtp-python
找到的 smtp 支持 outlook 发邮件的例子，验证可用

Dray <hnzksq@gmail.com> 於 2016年2月16日 週二 下午1:35寫道：

**Comment by Jackeriss** [comment]
@DrayChou

**Comment by Jackeriss** [comment]
可是pop不可用，还是没办法

**Comment by DrayChou** [comment]
https://github.com/DrayChou/emp_py
@Jackeriss 我重构了一个命令行版本，支持 Outlook 邮箱，可以正常发送收到命令，你参考下。
比较麻烦的一点是，不能太频繁发送邮件出去，要不然会被判断垃圾邮件，会要求邮箱所有者添加验证码做机器人检查。

**Comment by Jackeriss** [comment]
@DrayChou 我参照你的方法做了修改，现在支持加密了。

**Comment by DrayChou** [comment]
@Jackeriss 谢谢，我去更新下。

**Comment by Jackeriss** [comment]
@DrayChou 我又更新了，现在邮件是发给命令发送者了。我还新增了远程执行快捷键的功能。

**Comment by DrayChou** [comment]
嘿嘿，不错不错，加油哦。
命令执行的时候建议能加一个选项，是执行标题里后面的命令还是邮件正文。

Jack Criss notifications@github.com 於 2016年3月5日 週六 下午2:41寫道：
