### ISSUE TITLE
命令解析问题

### ISSUE THREAD

**Issue by DrayChou** [Jackeriss/Email_My_PC#4]
这里有几个问题。
1. if tag_cmd in subject:
    如果几个命令的设定分别为 #a #ab #abc #abcd ，那么发送过来的命令是 #abcd 的时候，会执行那个命令？
2. content = info[2] subprocess.Popen(content, shell=True)
    content 是解析出来的邮件内容，但是这个内容经常会带一些奇怪的字符进去，比如 <,换行符 等，那么这样的话执行命令的时候就会出错。

**Comment by Jackeriss** [comment]
1.都会执行，这样设置命令是不是为了一次执行多个操作啊？为什么要用命令覆盖命令呢？
2.已添加命令首尾空白字符与符号过滤。

**Comment by DrayChou** [comment]
1.理论上来说一次命令只执行一个操作啊。命令覆盖命令是因为你并没有完全校准命令啊。
2.符号过滤什么的比较麻烦，我是倾向于把命令参数直接跟在命令后面，放在标题里，比如： #cmd echo 123 > 1.txt

Jack Criss notifications@github.com 於 2016年2月19日 週五 下午1:30寫道：

**Comment by Jackeriss** [comment]
我主要是为了可以一封邮件同时拍照加截屏，省去发多个邮件的麻烦。所以标题中有对应命令标签就会执行。而正是因为如此我才将命令参数写在正文中，避免混乱。
