### ISSUE TITLE
QQ 邮箱成功连接服务器以后好像还是无法获取到邮件

### ISSUE THREAD

**Issue by hwk603** [Jackeriss/Email_My_PC#8]
白名单已添加，用163/gmail等向设置好的QQ邮箱发送#screen的邮件，没有任何回复。

**Comment by Jackeriss** [comment]
将本地的 DNS 更改为 114.114.114.114 与 114.114.115.115 应该可以解决这个问题。否则请看看软件根目录下是否生产了一个记录错误日志的 .log 文件。

**Comment by hwk603** [comment]
dns 是修改了的，软件根目录下没有log文件【所以就很奇怪

---

昨天还没有报错的，今天重新启动的时候就一直用户名密码错误了
